### ISSUE TITLE
Unresponsive main image

### ISSUE THREAD

**Issue by varjmes** [intermezzOS/intermezzOS.github.io#18]
Hello again!

Also noticed the image you had wasn't responsive, but didn't want to submit too many PRs (I thnink it can be kinda stressful when someone starts submitting a bunch of stuff to your very new project).

But here is a .gif of replication!

![intermezzosresponsiveimage](https://cloud.githubusercontent.com/assets/542140/12066603/7e69f224-afe2-11e5-8eb2-69163004f33f.gif)

To fix:
- Add `width: 100%; max-width: 497px;` to the `img` selector in your css.

![intermezzosresponsiveimage_after](https://cloud.githubusercontent.com/assets/542140/12066638/e7914702-afe2-11e5-85fc-3ed3c285499e.gif)

Happy to do this fix if you'd like me to :)

**Comment by steveklabnik** [comment]
> (I thnink it can be kinda stressful when someone starts submitting a bunch of stuff to your very new project).

I actually prefer it! So yes, send a PR if you have the time, that'd be fantastic :)

**Comment by varjmes** [comment]
Incoming!
