### ISSUE TITLE
Question about 2MiB

### ISSUE THREAD

**Issue by Digipom** [intermezzOS/intermezzOS.github.io#26]
On http://intermezzos.github.io/book/paging.html, we come across this part:

> mov eax, 0x200000  ; 2MiB
> We’re going to store 200,000 in eax. 

And there are further parts that refer to this as 200,000 bytes in size. I'm just wondering if this was intentional because 2MiB and 0x200000 would be 2,097,152. 

Thanks for the book so far, it is great! :)

**Comment by steveklabnik** [comment]
Hey @Digipom ! This is the repository for the website, not the book, so this is a bit mis-filed, but still :smile: 

We had another comment about this over in the book issues.... but I can't seem to find it right now... can you take a look? It should be correct https://github.com/intermezzos/book/issues

**Comment by Digipom** [comment]
Sorry about that. ;)

I can't find an issue but we do have this PR: https://github.com/intermezzOS/book/pull/110
